### ISSUE TITLE
New speakers not being displayed consistently

### ISSUE THREAD

**Issue by mkretz** [cloudnativebern/cloudnativeday.ch#40]
The following observation has been made: when the main page is loaded, no call to the `Speakers` endpoint is made and existing speakers seem to be loaded from cache (not including some recently confirmed ones). When we navigate to the Team page and then back to Speakers, a call to the `Speakers` endpoint is made, and all confirmed speakers are correctly displayed.

Sounds like a caching issue.

**Comment by cloudlena** [comment]
As discussed, this was most likely just a caching issue.
